-- Create user_credentials table for authentication
CREATE TABLE user_credentials (
    credential_id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_credentials_user FOREIGN KEY (user_id) REFERENCES user_table (user_id) ON DELETE CASCADE
);

-- Create index for faster lookup by user_id
CREATE INDEX idx_credentials_user_id ON user_credentials (user_id);

-- Insert sample credentials for existing test users
-- Password: "password123" hashed with BCrypt (generated by PasswordHashGenerator)
-- BCrypt hash for "password123": $2a$10$zhK7OkeeJ44/6BZzldAUGucL2MI5R2b5uj/mKo8P8VPq22p1gSIG.

INSERT INTO
    user_credentials (
        credential_id,
        user_id,
        password_hash,
        created_at,
        updated_at
    )
VALUES
    -- Nguyen Van An - EMPLOYEE (from V3 sample data)
    (
        'cred-0001-0001-0001-000000000001',
        'u1a2b3c4-e5f6-7890-abcd-ef1234567890',
        '$2a$10$zhK7OkeeJ44/6BZzldAUGucL2MI5R2b5uj/mKo8P8VPq22p1gSIG.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Tran Thi Binh - MANAGER (from V3 sample data)
    (
        'cred-0002-0002-0002-000000000002',
        'u2b3c4d5-f6a7-8901-bcde-f12345678901',
        '$2a$10$zhK7OkeeJ44/6BZzldAUGucL2MI5R2b5uj/mKo8P8VPq22p1gSIG.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Le Van Cuong - HR (from V3 sample data)
    (
        'cred-0003-0003-0003-000000000003',
        'u3c4d5e6-a7b8-9012-cdef-123456789012',
        '$2a$10$zhK7OkeeJ44/6BZzldAUGucL2MI5R2b5uj/mKo8P8VPq22p1gSIG.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Pham Thi Dung - HR (from V3 sample data)
    (
        'cred-0004-0004-0004-000000000004',
        'u4d5e6f7-b8c9-0123-def0-234567890123',
        '$2a$10$zhK7OkeeJ44/6BZzldAUGucL2MI5R2b5uj/mKo8P8VPq22p1gSIG.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Hoang Van Em - EMPLOYEE (from V3 sample data)
    (
        'cred-0005-0005-0005-000000000005',
        'u5e6f7a8-c9d0-1234-ef01-345678901234',
        '$2a$10$zhK7OkeeJ44/6BZzldAUGucL2MI5R2b5uj/mKo8P8VPq22p1gSIG.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    -- Bui Van Giang - ADMIN (from V3 sample data)
    (
        'cred-0006-0006-0006-000000000006',
        'u7a8b9c0-e1f2-3456-0123-567890123456',
        '$2a$10$zhK7OkeeJ44/6BZzldAUGucL2MI5R2b5uj/mKo8P8VPq22p1gSIG.',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );